language: rust
cache: cargo

matrix:
  include:
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=i686-pc-windows-msvc
      os: windows
    - env: TARGET=x86_64-pc-windows-msvc
      os: windows

script:
  - cargo build --verbose
